import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'tasklist',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <section className='flex flex-col items-center justify-center gap-4 py-8'>
          <Providers>{children}</Providers>
        </section>
      </body>
    </html>
  );
}
6